@startuml Book

!include book_id/BookId.puml
!include title/Title.puml
!include price/Price.puml

class "Book(書籍)" as Book << (R,red) RootEntity >> {
    BookId: BookId
    Title: タイトル
    Price: 価格
}

Book *-down- BookId
Book *-down- Title
Book *-down- Price

@enduml