version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432